replicaCount: 2

image:
  repository: your-dockerhub-user/myservice
  pullPolicy: Always
  tag: latest

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
